[2025-06-08T14:49:13.573+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-08T14:49:13.609+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_csv_to_postgres_dag.generate_insert_queries manual__2025-06-08T14:49:11+00:00 [queued]>
[2025-06-08T14:49:13.621+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_csv_to_postgres_dag.generate_insert_queries manual__2025-06-08T14:49:11+00:00 [queued]>
[2025-06-08T14:49:13.622+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-08T14:49:13.638+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_insert_queries> on 2025-06-08 14:49:11+00:00
[2025-06-08T14:49:13.643+0000] {standard_task_runner.py:63} INFO - Started process 945 to run task
[2025-06-08T14:49:13.646+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'simple_csv_to_postgres_dag', 'generate_insert_queries', 'manual__2025-06-08T14:49:11+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/simple_csv_to_postgres_dag.py', '--cfg-path', '/tmp/tmp21yw9pu6']
[2025-06-08T14:49:13.649+0000] {standard_task_runner.py:91} INFO - Job 263: Subtask generate_insert_queries
[2025-06-08T14:49:13.710+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_csv_to_postgres_dag.generate_insert_queries manual__2025-06-08T14:49:11+00:00 [running]> on host f6c4201d846e
[2025-06-08T14:49:13.803+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_csv_to_postgres_dag' AIRFLOW_CTX_TASK_ID='generate_insert_queries' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T14:49:11+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T14:49:11+00:00'
[2025-06-08T14:49:13.804+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-08T14:49:13.826+0000] {logging_mixin.py:188} INFO - Read 5 rows from sample_files/input.csv
[2025-06-08T14:49:13.828+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-08T14:49:13.829+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/simple_csv_to_postgres_dag.py", line 50, in generate_insert_queries
    with open(sql_file_path, 'w') as f:
PermissionError: [Errno 13] Permission denied: './dags/sql/insert_queries.sql'
[2025-06-08T14:49:13.839+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=simple_csv_to_postgres_dag, task_id=generate_insert_queries, run_id=manual__2025-06-08T14:49:11+00:00, execution_date=20250608T144911, start_date=20250608T144913, end_date=20250608T144913
[2025-06-08T14:49:13.852+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 263 for task generate_insert_queries ([Errno 13] Permission denied: './dags/sql/insert_queries.sql'; 945)
[2025-06-08T14:49:13.870+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-08T14:49:13.889+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2025-06-08T14:49:13.906+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-08T14:49:13.912+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
