[2025-06-08T10:59:09.922+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-08T10:59:09.971+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: large_csv_processor_dag.process_products_csv scheduled__2025-06-07T00:00:00+00:00 [queued]>
[2025-06-08T10:59:09.994+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: large_csv_processor_dag.process_products_csv scheduled__2025-06-07T00:00:00+00:00 [queued]>
[2025-06-08T10:59:09.994+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-08T10:59:10.010+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_products_csv> on 2025-06-07 00:00:00+00:00
[2025-06-08T10:59:10.014+0000] {standard_task_runner.py:63} INFO - Started process 339 to run task
[2025-06-08T10:59:10.017+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'large_csv_processor_dag', 'process_products_csv', 'scheduled__2025-06-07T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/csv_processor.py', '--cfg-path', '/tmp/tmp0_9vr32k']
[2025-06-08T10:59:10.019+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask process_products_csv
[2025-06-08T10:59:10.075+0000] {task_command.py:426} INFO - Running <TaskInstance: large_csv_processor_dag.process_products_csv scheduled__2025-06-07T00:00:00+00:00 [running]> on host 6211e2649837
[2025-06-08T10:59:10.163+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='large_csv_processor_dag' AIRFLOW_CTX_TASK_ID='process_products_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-07T00:00:00+00:00'
[2025-06-08T10:59:10.164+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-08T10:59:10.178+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-08T10:59:10.179+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/csv_processor.py", line 40, in process_csv_in_chunks
    with open(sql_file_path, 'w') as sql_file:
PermissionError: [Errno 13] Permission denied: './dags/sql/products_insert.sql'
[2025-06-08T10:59:10.190+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=large_csv_processor_dag, task_id=process_products_csv, run_id=scheduled__2025-06-07T00:00:00+00:00, execution_date=20250607T000000, start_date=20250608T105909, end_date=20250608T105910
[2025-06-08T10:59:10.208+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task process_products_csv ([Errno 13] Permission denied: './dags/sql/products_insert.sql'; 339)
[2025-06-08T10:59:10.246+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-08T10:59:10.266+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2025-06-08T10:59:10.285+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-08T10:59:10.288+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
